### ISSUE TITLE
Regional library systems not handled properly

### ISSUE THREAD

**Issue by pvoveris** [jdalbey/libbyfetch#5]
My library system shares the same overdrive account among the metro area library systems.  For instance the overdrive library for 'phoenix' asks the user to choose one of eight library systems in the metro area.  After choosing one of the eight, then it progresses to the enter card number.  The program currently fails at the entering card number stage.

**Comment by jdalbey** [comment]
I'm sorry that the program doesn't handle this situation.  The libraries where I did my testing don't exhibit this behavior.  Here is what I see when I try to use the phoenix library:
![phoenix1](https://github.com/user-attachments/assets/950b8657-f17e-4ef3-85bf-b82ebddfd411)
After choosing a library the card number prompt appears:
![phoenix2](https://github.com/user-attachments/assets/1dfd0f87-8dc5-45f4-9eed-01ed53e1851c)
In order to proceed can you provide more information?  
1.  Does each branch library require a separate library card number or do all libraries in the region share a single card number?  Can you login to any branch with the same card number?
2. Once you have successfully entered your card number and PIN does the browser display the page with URL  `https://libbyapp.com/library/phoenix` regardless of which branch you signed in with?

**Comment by pvoveris** [comment]
Hi there, thanks for looking at this.

1.  Yes, each library district has their own library cards, and are used at
those libraries.  So you cannot use one library card at a different city
each are unique.
2. Once entering the number/pin or password for a specific library it then
shows you a picture of a library card with a next button, as the photo
shows.

If you would like to test your changes, I would be happy to provide the log
in details for my account.

**Comment by pvoveris** [comment]
![librarycard](https://github.com/user-attachments/assets/53cdcf8c-aaa2-404b-847b-057c6894f3d6)

**Comment by jdalbey** [comment]
Thanks for that additional info: each branch has a separate library card. 
That would be terrific if you would share your library card number and PIN.  (I don't know how I could test the code without it).  If you post the details in a comment here, I will delete the comment once I've noted the details.

**Comment by pvoveris** [comment]
PACREG1861848
8vqWBwxME6Yb

**Comment by jdalbey** [comment]
Thanks! Got it.  Which branch library is this login associated with?

**Comment by pvoveris** [comment]
Phoenix

**Comment by jdalbey** [comment]
My idea for a solution is to have you modify the library_card_config.txt file by adding a fourth field that is the name of the library branch with which the card is associated.  Example:
lapl,11122233344,9876,Canoga Park Library

Does that seem like a reasonable approach to you?

**Comment by jdalbey** [comment]
An alternative would be to have the program display the list of branches and have the user select the appropriate one.. That way no modification to the config file would be needed.

**Comment by pvoveris** [comment]
I was thinking that a fourth item in the config file was the way to go
considering that the details are already for a specific library.  THe
option to display the other libraries is good, but the rest of the info in
the config file is for a specific library, so the choice could be
confusing, unless you really want to go wild and add the ability to code
multiple libraries into the config file.

**Comment by jdalbey** [comment]
One disadvantage of requiring the user to modify the config file is that the spelling must be accurate.  In my experience, spelling errors are common.  It is usually more reliable to list the choices for the user and let them pick from a list.

**Comment by jdalbey** [comment]
I'm working on alternative two.  Here's what the output will look like:
```
Initializing LibbyApp.
Reading library card configuration file.
Loading library page for 'phoenix'
Starting signin to Greater Phoenix Digital Library.
Branch libraries are:
    1. Apache Junction Public Library
    2. Casa Grande Public Library
    3. Glendale Public Library
    4. Maricopa County Library District
    5. Mesa Public Library
    6. Peoria Public Library
    7. Phoenix Public Library
    8. Scottsdale Public Library System
Where do you use your library card (Enter a number 1-8)? 5
Okay, signing in to Mesa Public Library
...

```
Do you have any suggestions for improvement?

**Comment by pvoveris** [comment]
I think it's perfect!

**Comment by flyswimr** [comment]
I use a regional library system with a library card that works at one branch (as well as a non-regional system with one card for one branch), happy to test code changes.   Prefer the fourth entry in the config file but it doesn't really matter at this point since the config file is for a single library.

**Comment by jdalbey** [comment]
@flyswimr I would appreciate it if you would try out the enhancement for regional libraries.  It's the `libbyfetch.py` file in main.   No change to the config file is needed.

**Comment by flyswimr** [comment]
It works for my regional library, My regional lists eight libraries also like the Phoenix library system.  Great!

**Comment by jdalbey** [comment]
Nice.  Thanks for the pilot test and feedback.

**Comment by pvoveris** [comment]
I can confirm it works for my libraries as well, thanks for updating this!

**Comment by jdalbey** [comment]
@pvoveris Great, I'm glad this works for you.  I appreciate your testing it for me. I would never have known about regional libraries if you hadn't alerted me to this issue.

**Comment by jdalbey** [comment]
Update in 93963d7f577d55ab151aaf2e09c2d8d6486b759a
A new feature now checks to see if the library page offers multiple branches and if so displays a list from which the user chooses the branch to which they want to login.  
Example:
```
Initializing LibbyApp.
Reading library card configuration file.
Loading library page for 'lasvegas'
Starting signin to Las Vegas-Clark County Library District.
Branch libraries are:
    1. Boulder City
    2. Las Vegas - Clark County
    3. North Las Vegas Library District
Where do you use your library card (Enter a number 1-3)?
```

**Comment by jdalbey** [comment]
@pvoveris I think my solution for regional libraries may not be flexible enough.  Since the regional library (Greater Phoenix Digital Library) has multiple branches, isn't it possible that someone may have a library card at more than one branch?  Perhaps I have a card at the Phoenix public library but also one at Glendale public library.  In Overdrive these are both 'phoenix' and thus, currently, there is only one entry in the config file. The current solution doesn't allow someone to have separate cards for each branch.

**Comment by pvoveris** [comment]
The changes you made allowed your program to continue as there was an intermediate step introduced to the flow, i.e. district library choice.  It still requires the config file to have the details of only one of those libraries.  If they had multiple cards, then they would need multiple config files and swap them manually before running the program.  Now if you wanted to allow multiple entries in the config file, then you could list them all at program start and have the user select the details to use, but that would require a fourth entry in the config to distinguish the library for those details.

**Comment by jdalbey** [comment]
Since the original issue has been resolved I'm going to close this issue.  I have opened a separate issue (#14) for the concern around multiple library cards from the same regional library.
