### ISSUE TITLE
Pycurl Can't load CA certificate file

### ISSUE THREAD

**Issue by warthog3** [jdalbey/libbyfetch#6]
Not sure if this is a problem with my current installation or with the program. Getting the following error after I select a book to download:

`Download progress: An error occurred for an unknown cause.
Exception type:  <class 'pycurl.error'>
Message: (77, "SSL: can't load CA certificate file /etc/ssl/certs/ca-certificates.crt")
Traceback (most recent call last):
  File "/Users/user/libbyfetch/libbyfetch.py", line 387, in <module>
    fetch_audio_files(book_title, deweyURL, cookie)
  File "/Users/user/libbyfetch/libbyfetch.py", line 338, in fetch_audio_files
    do_pycurl_cmd(audio_filename, currentURL, cookie)
  File "/Users/user/libbyfetch/libbyfetch.py", line 317, in do_pycurl_cmd
    c.perform()
pycurl.error: (77, "SSL: can't load CA certificate file /etc/ssl/certs/ca-certificates.crt")`

I've tried updating Homebrew, MacOS, X-Code, curl, pycurl and all of the other dependencies. Any ideas would be appreciated.

**Comment by jdalbey** [comment]
Let me suggest a few things.
Does a simple `curl` command work? 
Try `curl https://www.google.com`
If this also fails, it's a system-wide issue with CA certificates.

Check if the file exists at the path indicated in the error message:
`ls -l /etc/ssl/certs/ca-certificates.crt`
    If it does not exist, you may need to install or update the CA certificates. On most Linux systems, use:
    `sudo apt update && sudo apt install ca-certificates -y`

Let me know the results of these efforts.

**Comment by BenjaminMichaelis** [comment]
I experienced a similar result - on linux and then windows. My hacky workaround (definitely not long term ideal) on windows was to go find a ca-bundle.crt already on my machine and use that. Linux I haven't finished debugging since I got the windows side working quickly (but need to go back around and find a more long term solution)

**Comment by flyswimr** [comment]
Like @BenjaminMichaelis mentioned, Windows 11 was easy to set up for a non-regional library system, but a little hacky: (1) install python + dependencies (2) install Chrome (3) copy ca-certificates.crt from a linux machine (or could try a hard link in Linux on a shared folder in a virtual machine).  (4) change libbyfetch.py code to point to the cert.

    # c.setopt(c.CAINFO, '/etc/ssl/certs/ca-certificates.crt')
    c.setopt(c.CAINFO, 'Z://libbyfetch/ca-certificates.crt')  

I wasn't sure about trying to get this to work on Ubuntu 24 since Chromium is a snap package now, and spent too much time getting the python virtual environment right.

It works @jdalbey, nice work!

**Comment by jdalbey** [comment]
I'm working on an enhancement to resolve this issue in branch dev_issue6.

**Comment by tcjjr** [comment]
After some trial and error, I got this to work in Windows 11 by installing certifi (_pip install certifi_), running _python -m certifi_ to locate the certificate store that certifi had installed, and then replacing the CA certificate bundle path in libbyfetch.py to point to that path instead.: 

    # c.setopt(c.CAINFO, '/etc/ssl/certs/ca-certificates.crt')
    c.setopt(c.CAINFO, '/Python312/Lib/site-packages/certifi/cacert.pem')

(My Windows Python installation is at c:/Python312. Yours may be elsewhere, depending upon the version.)

After that, it worked fine and I was able to download the audiobook MP3s that I wanted.

**Comment by jdalbey** [comment]
@tcjjr I'm so glad you could obtain your MP3!  
The fix I'm working on that should be platform independent:
`c.setopt(c.CAINFO, certifi.where())`
It's in branch dev_issue6 waiting for me to test it on different platforms.

**Comment by jdalbey** [comment]
Fixed in 3009de5c0b7a312ac2792b099cd39c78c9c8798e.  Used `certifi` module to get cross-platform CA bundle.
